// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace UEDS
{
	public class ColorSerializer : IPrimitveSerializer
	{
		public ColorSerializer ()
		{
		}

		#region IPrimitveSerializer implementation


		public System.Type HandledType ()
		{
			return typeof(Color);
		}

		public List<SerializedPrimitive> Serialize (object pValue)
		{
			var list = new List<SerializedPrimitive>();
			Color v = (Color)pValue;
			list.Add(Primitive("r",v.r));
			list.Add(Primitive("g",v.g));
			list.Add(Primitive("b",v.b));
			list.Add(Primitive("a",v.a));
			return list;
		}

		SerializedPrimitive Primitive(string pName, object pValue)
		{
			return new SerializedPrimitive(pName, pValue);
		}

		public object Deserialize (List<SerializedPrimitive> pValue)
		{
			Color v = new Color();
			v.r = System.Convert.ToSingle( pValue[0].mValue );
			v.g = System.Convert.ToSingle( pValue[1].mValue );
			v.b = System.Convert.ToSingle( pValue[2].mValue );
			v.a = System.Convert.ToSingle( pValue[3].mValue );
			return v;
		}

		#endregion
	}
}

