// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace UEDS
{
	public class Vector3Serializer : IPrimitveSerializer
	{
		public Vector3Serializer ()
		{
		}

		#region IPrimitveSerializer implementation


		public System.Type HandledType ()
		{
			return typeof(Vector3);
		}

		public List<SerializedPrimitive> Serialize (object pValue)
		{
			var list = new List<SerializedPrimitive>();
			Vector3 v = (Vector3)pValue;
			list.Add(Primitive("x",v.x));
			list.Add(Primitive("y",v.y));
			list.Add(Primitive("z",v.z));
			return list;
		}

		SerializedPrimitive Primitive(string pName, object pValue)
		{
			return new SerializedPrimitive(pName, pValue);
		}

		public object Deserialize (List<SerializedPrimitive> pValue)
		{
			Vector3 v = new Vector3();
			v.x = System.Convert.ToSingle( pValue[0].mValue );
			v.y = System.Convert.ToSingle( pValue[1].mValue );
			v.z = System.Convert.ToSingle( pValue[2].mValue );
			return v;
		}

		#endregion
	}
}

